### ISSUE TITLE
Install Problem node-gyp error

### ISSUE THREAD

**Issue by AquilaSagitta** [cgross/generator-cg-angular#100]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>npm install -g generator-cg-angular
/
> fidonet-mailer-binkp-crypt@0.0.23 install C:\Users\cblahut\AppData\Roaming\npm
\node_modules\generator-cg-angular\node_modules\yeoman-generator\node_modules\do
wnload\node_modules\decompress\node_modules\adm-zip\node_modules\fidonet-mailer-
binkp-crypt
> node-gyp configure build

C:\Users\cblahut\AppData\Roaming\npm\node_modules\generator-cg-angular\node_modu
les\yeoman-generator\node_modules\download\node_modules\decompress\node_modules\
adm-zip\node_modules\fidonet-mailer-binkp-crypt>node "C:\nodejs\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build

child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'crypt.vcxproj' is inva
lid.  Platform='x64'. You may be seeing this message because you are trying to
build a project without a solution file, and have specified a non-default Platf
orm that doesn't exist for this project. [C:\Users\cblahut\AppData\Roaming\npm\
node_modules\generator-cg-angular\node_modules\yeoman-generator\node_modules\do
wnload\node_modules\decompress\node_modules\adm-zip\node_modules\fidonet-mailer
-binkp-crypt\build\crypt.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\cblahut\AppData\Roaming\npm\node_modules\generator-cg-angu
lar\node_modules\yeoman-generator\node_modules\download\node_modules\decompress\
node_modules\adm-zip\node_modules\fidonet-mailer-binkp-crypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install" "-g" "generator-cg-angular"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! fidonet-mailer-binkp-crypt@0.0.23 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fidonet-mailer-binkp-crypt@0.0.23 install script 'node-gy
p configure build'.
npm ERR! This is most likely a problem with the fidonet-mailer-binkp-crypt packa
ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fidonet-mailer-binkp-crypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

Not sure why its throwing these errors. Any help is appreciated!

**Comment by cgross** [comment]
Hmm.  Try this Stackoverflow post.  Seems like its the same root issue:

http://stackoverflow.com/questions/28407965/npm-install-g-generator-x-error-in-windows

**Comment by AquilaSagitta** [comment]
I noticed had the same issue with the generator-angular so reinstalling node

**Comment by AquilaSagitta** [comment]
thanks @cgross thank thread helped me solve this issue! How to fix:
[I was in project directory]
npm install --save-dev adm-zip@0.4.4
npm install generator-cg-angular
