### ISSUE TITLE
grunt build issues

### ISSUE THREAD

**Issue by DrAlexMV** [cgross/generator-cg-angular#34]
Although `grunt build` works, the distribution created in the `dist` folder seems to have a few issues that I cannot wrap my head around. 

Firstly, it is not able to find partials. After looking at the building pipeline, I notice that the html partials should have been made into `ng-templates` using the grunt module. Also, upon close inspection with a breakpoint, I notice that my `angular.js` file throws the an error along the lines of `'ngLocale module not found'`. 

None of these issues actually happen when I just run `grunt serve` on the non production version.

Any clues?

Update: I am using the latest version - `generator-cg-angular@3.1.0`

Update II: Adding some pictures to really narrow down on the issue. 
![cg-angular-bug2](https://cloud.githubusercontent.com/assets/1136898/3166304/4f6425ce-eb5f-11e3-9cdd-ec66a15bc754.jpg)

![cg-angular-bug](https://cloud.githubusercontent.com/assets/1136898/3166305/4f649e46-eb5f-11e3-9ca2-b784d693ec48.jpg)

**Comment by mikehm** [comment]
I am not able to see the views (minified templates?) that were created for individual modules in the dist folder after doing 'grunt build'.

**Comment by cgross** [comment]
They're turned into JavaScript using the ngTemplates task. They're inside you full minified JavaScript file.

**Comment by mikehm** [comment]
Thanks,

I am able to serve the app from the dist folder (with 'grunt serve') and it works well. But again, when trying to build, I get the unknown provider error:

"Error: [$injector:unpr] Unknown provider: aProvider <- a"

The app is client only at this time, and not connected to any web service. I made sure no undefined services are injected inside the controllers. Or, do I still need to use the array syntax (for injecting $scope and other services )inside the controllers?

**Comment by cgross** [comment]
It is automatically taken care of by the ng-annotate task during the grunt build.  But it looks like there's some bug/issue.  Tools like ng-annotate can get confused and it might miss a spot.  I'd suggest you first find what method is triggering that error (i.e. which controller, etc).  Then try to see if there's something weird, why ng-annotate is having problems with.  

To figure out where its occurring, you can tweak the minification options to include beautify=true.  That should allow you to debug where this is happening.
